### ISSUE TITLE
TAB menu don't show up in alpha 1.2.6 and beta 1.2_02 (don't checked in other versions)

### ISSUE THREAD

**Issue by Strongleong** [codieradical/MineOnline#251]
I don't know if it is ok, you don't write version  that's support it.

**Comment by codieradical** [comment]
The menu only shows up when playing on a server on the server list.
https://mineonline.codie.gg/servers
If it's not listed, there's no way for me to know who's online.
If the server is unlisted, you can find instructions on listing it here:
https://mineonline.codie.gg/serverhosting

Closing due to could not replicate. If you can confirm that the server is in fact listed, please reopen with more info.

Thanks for the report!
